# Generated by Django 4.2.2 on 2023-06-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний урок'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало курса'),
        ),
    ]
