# Generated by Django 4.2.2 on 2023-06-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
